name: Generate Json Docs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  

jobs:

  generate_json:
    name: Generate Json Docs
    runs-on: ubuntu-latest
    env:
      EA_LOGIN_PASS: ${{ secrets.EA_LOGIN_PASS }}
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}        

      - name: setup chrome
        uses: browser-actions/setup-chrome@latest

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Build Json docs
        run: |
          source .venv/bin/activate
          python libs/json_docs_generator.py

      - name: Commit and push changes
        run: |
          git fetch --prune --unshallow
          git add .
          git diff
          git config --global user.email "ranger@bfportal.gg"
          git config --global user.name "Ranger"
          git commit -m "Successfully generated docs 🎉" -a || echo "No changes to commit"
          git push          
      
