name: Generate Json Docs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  

jobs:

  generate_json:
    name: Generate Json Docs
    runs-on: ubuntu-latest
    env:
      REMID: ${{ secrets.REMID }}
      SID: ${{ secrets.SID }}
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
      - name: Install xvfb
        run: sudo apt-get install xvfb      

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install all necessary packages
        run: pip install -r requirements.txt

      - name: Build Json docs
        run: CHROME_BIN=$(which chrome) python libs/json_docs_generator.py

      - name: Commit and push changes
        run: |
          git fetch --prune --unshallow
          git add .
          git diff
          git config --global user.email "ranger@bfportal.gg"
          git config --global user.name "Ranger"
          git commit -m "Successfully generated docs 🎉" -a || echo "No changes to commit"
          git push          
      
