name: ScrapeBlockNames
on:
  workflow_dispatch:
jobs:
  
  
  get_enabled_blocks:
    runs-on: ubuntu-latest
    env:
      BFPORTAL_EMAIL: ${{ secrets.BFPORTAL_EMAIL }}
      BFPORTAL_PASSWORD: ${{ secrets.BFPORTAL_PASSWORD }}
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      # Chromium is already installed!
      # - name: Install software
      #   run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install -r requirements.txt
      - name: Run the scraping script
        run: python libs/get_block_names.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-artifact
          path: data/
  

  generate_data:
    needs: get_enabled_blocks
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: data-artifact
          path: data/
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install all necessary packages
        run: pip install -r requirements.txt
      - name: Generating Data
        run: python libs/gen_data.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-artifact
          path: data/
  
  
  generate_docs:
    needs: generate_data

    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Download data artifact
        uses: actions/download-artifact@v3
        with:
          name: data-artifact
          path: data/
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install all necessary packages
        run: pip install -r requirements.txt
      - name: Generating Docs
        run: python libs/gen_docs.py    

      - name: Upload data artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-artifact
          path: data/
      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-artifact
          path: docs/



  
  commit_changes:
    needs: generate_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download data artifact
        uses: actions/download-artifact@v3
        with:
          name: data-artifact
          path: data/
      - name: Download docs artifact
        uses: actions/download-artifact@v3
        with:
          name: data-artifact
          path: docs/
      
      - run: |
          git fetch --prune --unshallow
      - name: Commit and push changes
        run: |
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Successfully generated docs 🎉🎉🎉" -a || echo "No changes to commit"
          git push          
    
